### ISSUE TITLE
Supporting python3

### ISSUE THREAD

**Issue by TomyYamy** [nickovic/rtamt#10]
I know current ROS1 works on python 2.7. However STL independent use-case is also considerable. In that sense, python 2.7 is old and python3 is common. I know it is low priority.

FYI, I found the error below even antr4 is set up.
```
 python3 simple_STLeval.py 
Traceback (most recent call last):
  File "simple_STLeval.py", line 5, in <module>
    from rtamt_stl_pymon.spec.stl_specification import STLSpecification
  File "/mnt/data/repos/mondiro/code/catkin_ws/src/rtamt_stl_pymon/src/rtamt_stl_pymon/spec/stl_specification.py", line 13, in <module>
    from antlr4 import *
  File "/usr/local/lib/python3.5/dist-packages/antlr4/__init__.py", line 3, in <module>
    from antlr4.BufferedTokenStream import TokenStream
  File "/usr/local/lib/python3.5/dist-packages/antlr4/BufferedTokenStream.py", line 43, in <module>
    from antlr4.error.Errors import IllegalStateException
  File "/usr/local/lib/python3.5/dist-packages/antlr4/error/Errors.py", line 30, in <module>
    from antlr4.atn.Transition import PredicateTransition
  File "/usr/local/lib/python3.5/dist-packages/antlr4/atn/Transition.py", line 44, in <module>
    from __builtin__ import unicode
ImportError: No module named '__builtin__' 
```
I remember VerifAI needs python 3.5

**Comment by TomyYamy** [comment]
pyt23 supports python3.
