### ISSUE TITLE
rtamt/tests/python/ast/test_ast_visitor.py

### ISSUE THREAD

**Issue by TomyYamy** [nickovic/rtamt#146]
current refactoring branch does not pass the test case.

        $ rtamt/tests/python/ast$ python2 test_ast_visitor.py
        F
        ======================================================================
        FAIL: test_visitor_with_dence_time_stl (__main__.TestPrintAstVisitor)
        ----------------------------------------------------------------------
        Traceback (most recent call last):
          File "test_ast_visitor.py", line 36, in test_visitor_with_dence_time_stl
            self.assertEqual(out, '[\'Always((Variable)Predicate(Constant))\']', 'stl assertion')
        AssertionError: stl assertion
        
        ======================================================================
        FAIL: test_visitor_with_discrete_time_stl (__main__.TestPrintAstVisitor)
        ----------------------------------------------------------------------
        Traceback (most recent call last):
          File "test_ast_visitor.py", line 28, in test_visitor_with_discrete_time_stl
            self.assertEqual(out, '[\'Always((Variable)Predicate(Constant))\']', 'stl assertion')
        AssertionError: stl assertion
        
        ======================================================================
        FAIL: test_visitor_with_ltl (__main__.TestPrintAstVisitor)
        ----------------------------------------------------------------------
        Traceback (most recent call last):
          File "test_ast_visitor.py", line 20, in test_visitor_with_ltl
            self.assertEqual(out, '[\'Always((Variable)Predicate(Constant))\']', 'ltl assertion')
        AssertionError: ltl assertion
        
        ----------------------------------------------------------------------
        Ran 3 tests in 0.021s
        
        FAILED (failures=3)

**Comment by TomyYamy** [comment]
We are done.
