### ISSUE TITLE
'not eventually(always(x))' does not work.

### ISSUE THREAD

**Issue by TomyYamy** [nickovic/rtamt#25]
'not eventually(always(x))' does not work.

**Comment by TomyYamy** [comment]
I put the reproducible code in branch issue_no25.
```
$ python2 issue_noxx.py
Traceback (most recent call last):
  File "issue_noxx.py", line 19, in <module>
    rob = spec.offline(['a', data['a']])
  File "/xxx/python2.7/site-packages/rtamt/spec/stl_ct/specification.py", line 57, in offline
    out = self.offline_evaluator.offline(self.top, None)
  File "/xxx/python2.7/site-packages/rtamt/spec/stl_ct/offline.py", line 13, in offline
    sample = self.visit(element, args)
  File "/xxx/python2.7/site-packages/rtamt/spec/stl/visitor.py", line 39, in visit
    out = self.visitNot(element, args)
  File "/xxx/python2.7/site-packages/rtamt/spec/stl_ct/offline.py", line 65, in visitNot
    in_sample = self.visit(element.children[0], args)
  File "/xxx/python2.7/site-packages/rtamt/spec/stl/visitor.py", line 51, in visit
    out = self.visitEventually(element, args)
  File "/xxx/python2.7/site-packages/rtamt/spec/stl_ct/offline.py", line 100, in visitEventually
    in_sample = self.visit(element.children[0], args)
  File "/xxx/python2.7/site-packages/rtamt/spec/stl/visitor.py", line 59, in visit
    out = self.visitHistorically(element, args)
  File "/xxx/python2.7/site-packages/rtamt/spec/stl_ct/offline.py", line 121, in visitHistorically
    in_sample = self.visit(element.children[0], args)
  File "/xxx/python2.7/site-packages/rtamt/spec/stl/visitor.py", line 35, in visit
    out = self.visitPredicate(element, args)
  File "/xxx/python2.7/site-packages/rtamt/spec/io_stl_ct/offline.py", line 11, in visitPredicate
    out_sample = super(STLIOCTOffline, self).visitPredicate(element, args)
  File "/xxx/python2.7/site-packages/rtamt/spec/stl_ct/offline.py", line 23, in visitPredicate
    out_sample = element.node.offline(in_sample)
AttributeError: 'PredicateOperation' object has no attribute 'offline'
```

**Comment by TomyYamy** [comment]
Actually the formula is 'not eventually(always(x<A))'
I find work-around 'always(eventually(x>A))' is OK.

**Comment by TomyYamy** [comment]
I understand the limitation comes from online-STL semantics.
However I'd like to evaluate at least,
G(p), GF[0,d](p), FG[0,d](p), F(p) 
I wonder if we can discuss how to find workaround.

**Comment by TomyYamy** [comment]
What do you think this restriction?
The top of time operator or every time operator must have bounded time interval [o:h].
In that case, maybe evaluator can have just bounded time trajectory.

I do not have confidence, I did not check the semantics in detail.

**Comment by nickovic** [comment]
Nesting of unbounded future operators is now forbidden (as it should be). Unbounded "always" and "eventually" operators are now allowed only as top formula operators.
