### ISSUE TITLE
STL interval parameter does not allow decimal point.

### ISSUE THREAD

**Issue by TomyYamy** [nickovic/rtamt#27]
like
'''
spec.spec = 'out = always\[0:1.5](a<0.0)'
'''
The error is 
'''
$ python issue_no27.py
Traceback (most recent call last):
  File "issue_no27.py", line 17, in <module>
    spec.parse()
  File "/xxx/python2.7/site-packages/rtamt/spec/io_stl_ct/specification.py", line 34, in parse
    super(STLIOCTSpecification, self).parse()
  File "/xxx/python2.7/site-packages/rtamt/spec/stl_ct/specification.py", line 27, in parse
    super(STLCTSpecification, self).parse()
  File "/xxx/python2.7/site-packages/rtamt/spec/stl/specification.py", line 64, in parse
    ctx = parser.stlfile()
  File "/xxx/python2.7/site-packages/rtamt/parser/stl/StlParser.py", line 298, in stlfile
    self.stlSpecification()
  File "/xxx/python2.7/site-packages/rtamt/parser/stl/StlParser.py", line 403, in stlSpecification
    self.assertion()
  File "/xxx/python2.7/site-packages/rtamt/parser/stl/StlParser.py", line 568, in assertion
    self.expression(0)
  File "/xxx/python2.7/site-packages/rtamt/parser/stl/StlParser.py", line 1599, in expression
    self.interval()
  File "/xxx/python2.7/site-packages/rtamt/parser/stl/StlParser.py", line 1051, in interval
    self.intervalTime()
  File "/xxx/python2.7/site-packages/rtamt/parser/stl/StlParser.py", line 1117, in intervalTime
    self._errHandler.reportError(self, re)
  File "/usr/local/lib/python2.7/dist-packages/antlr4/error/ErrorStrategy.py", line 146, in reportError
    self.reportInputMismatch(recognizer, e)
  File "/usr/local/lib/python2.7/dist-packages/antlr4/error/ErrorStrategy.py", line 287, in reportInputMismatch
    recognizer.notifyErrorListeners(msg, e.offendingToken, e)
  File "/usr/local/lib/python2.7/dist-packages/antlr4/Parser.py", line 318, in notifyErrorListeners
    listener.syntaxError(self, offendingToken, line, column, msg, e)
  File "/usr/local/lib/python2.7/dist-packages/antlr4/error/ErrorListener.py", line 85, in syntaxError
    delegate.syntaxError(recognizer, offendingSymbol, line, column, msg, e)
  File "/xxx/python2.7/site-packages/rtamt/parser/stl/error/parser_error_listener.py", line 6, in syntaxError
    raise STLParseException (str(line) + ":" + str(column) + ": Syntax ERROR, " + str(msg))
rtamt.exception.stl.exception.STLParseException: 1:15: Syntax ERROR, mismatched input '1.5' expecting IntegerLiteral
'''
The example is branch issue_no27

**Comment by nickovic** [comment]
Added support for decimal point bounds. See examples of use in examples/features/timing_bound.
