### ISSUE TITLE
Parser Error - AttributeError: 'Eventually' object has no attribute 'node'

### ISSUE THREAD

**Issue by BentleyJOakes** [nickovic/rtamt#32]
Thank you for this useful project.

When I try to use the `eventually operator`, I get the following error. This is with an rtamt installation from today.
```
Traceback (most recent call last):
  File "mwe.py", line 70, in <module>
    p.prove([spec], var_types, var_types)
  File "mwe.py", line 32, in prove
    rob = spec.offline(self.data)
  File "/home/boakes/Software/miniconda3/lib/python3.7/site-packages/rtamt-0.0.11-py3.7.egg/rtamt/spec/stl/specification.py", line 240, in offline
  File "/home/boakes/Software/miniconda3/lib/python3.7/site-packages/rtamt-0.0.11-py3.7.egg/rtamt/spec/stl/specification.py", line 92, in update
  File "/home/boakes/Software/miniconda3/lib/python3.7/site-packages/rtamt-0.0.11-py3.7.egg/rtamt/spec/stl/evaluator.py", line 23, in evaluate
  File "/home/boakes/Software/miniconda3/lib/python3.7/site-packages/rtamt-0.0.11-py3.7.egg/rtamt/spec/stl/visitor.py", line 52, in visit
  File "/home/boakes/Software/miniconda3/lib/python3.7/site-packages/rtamt-0.0.11-py3.7.egg/rtamt/spec/stl/evaluator.py", line 145, in visitEventually
AttributeError: 'Eventually' object has no attribute 'node'
```

Here is an example of the failing specification. If the first `eventually` is changed to `always`, the specification succeeds in parsing.
`out = eventually((AmbientTemperatureSignal1>0) implies eventually[0:5](AmbientTemperatureSignal1==1))`

The attached mwe.py and mwe.csv are a minimum working example.

Please let me know any other information you need.
[mwe.zip](https://github.com/nickovic/rtamt/files/4772708/mwe.zip)

**Comment by nickovic** [comment]
Resolves the issue. Thanks for pointing it out.

**Comment by nickovic** [comment]
The master branch now incorporates the fix for this bug.
