### ISSUE TITLE
online_monitor_ct.py does not work on python2

### ISSUE THREAD

**Issue by TomyYamy** [nickovic/rtamt#35]
master [5366349c44afb53cffa5fb29e43fea1eb23b6c52]
online_monitor_ct.py does not work on python2. (in python3 case, it works)
```
/rtamt/examples/online_monitors$ python2 online_monitor_ct.py 
Robustness offline: [[2.0, 3.0], [3.5, 1.0], [4.3, -0.10000000000000009], [8.9, -0.10000000000000009]]
Traceback (most recent call last):
  File "online_monitor_ct.py", line 99, in <module>
    monitor()
  File "online_monitor_ct.py", line 64, in monitor
    rob = spec.update(['req', req_1], ['gnt', gnt_1])
  File "/usr/local/lib/python2.7/dist-packages/rtamt/spec/stl_ct/specification.py", line 41, in update
    out = self.evaluator.evaluate(self.top, ['update'])
  File "/usr/local/lib/python2.7/dist-packages/rtamt/spec/stl_ct/evaluator.py", line 13, in evaluate
    sample = self.visit(element, args)
  File "/usr/local/lib/python2.7/dist-packages/rtamt/spec/stl/visitor.py", line 54, in visit
    out = self.visitAlways(element, args)
  File "/usr/local/lib/python2.7/dist-packages/rtamt/spec/stl_ct/evaluator.py", line 167, in visitAlways
    in_sample = self.visit(element.children[0], args)
  File "/usr/local/lib/python2.7/dist-packages/rtamt/spec/stl/visitor.py", line 46, in visit
    out = self.visitImplies(element, args)
  File "/usr/local/lib/python2.7/dist-packages/rtamt/spec/stl_ct/evaluator.py", line 128, in visitImplies
    in_sample_1 = self.visit(element.children[0], args)
  File "/usr/local/lib/python2.7/dist-packages/rtamt/spec/stl/visitor.py", line 58, in visit
    out = self.visitOnce(element, args)
  File "/usr/local/lib/python2.7/dist-packages/rtamt/spec/stl_ct/evaluator.py", line 186, in visitOnce
    in_sample = self.visit(element.children[0], args)
  File "/usr/local/lib/python2.7/dist-packages/rtamt/spec/stl/visitor.py", line 36, in visit
    out = self.visitPredicate(element, args)
  File "/usr/local/lib/python2.7/dist-packages/rtamt/spec/io_stl_ct/evaluator.py", line 11, in visitPredicate
    out_sample = super(STLIOCTEvaluator, self).visitPredicate(element, args)
  File "/usr/local/lib/python2.7/dist-packages/rtamt/spec/stl_ct/evaluator.py", line 26, in visitPredicate
    out_sample = element.node.update(in_sample_1, in_sample_2)
  File "/usr/local/lib/python2.7/dist-packages/rtamt/operation/stl_ct/predicate_operation.py", line 27, in update
    out_val = in_sample[1] - self.threshold
AttributeError: 'PredicateOperation' object has no attribute 'threshold'
```

I don't have enough confidence about installing... If it is because of that I'm sorry.

**Comment by TomyYamy** [comment]
Just FYI, I go back master [e152433efd7862ffd1f0d54020b04a352f466a3d] and it works.

**Comment by nickovic** [comment]
This should work now. Please make sure that you do sudo pip2 install . --upgrade

**Comment by TomyYamy** [comment]
Do you mean ros-integrate branch commit [8988473487854d0fb99b3ae30cdce788d9bb2d0f]?
I find still there is another issue.
```
rtamt/examples/online_monitors$ ./online_monitor_ct.py 
Robustness offline: [[2.0, 3.0], [3.5, 1.0], [4.3, -0.10000000000000009], [8.9, -0.10000000000000009]]
Traceback (most recent call last):
  File "./online_monitor_ct.py", line 99, in <module>
    monitor()
  File "./online_monitor_ct.py", line 64, in monitor
    rob = spec.update(['req', req_1], ['gnt', gnt_1])
  File "/usr/local/lib/python2.7/dist-packages/rtamt/spec/stl_ct/specification.py", line 41, in update
    out = self.evaluator.evaluate(self.top, ['update'])
  File "/usr/local/lib/python2.7/dist-packages/rtamt/spec/stl_ct/evaluator.py", line 25, in evaluate
    out_sample = sample
UnboundLocalError: local variable 'sample' referenced before assignment
```

**Comment by TomyYamy** [comment]
I push commit [22752023fb92f2dd4f4678838f76206e3ba9dbfc]. Please check whether it is right or not.

**Comment by nickovic** [comment]
problem solved - I introduced a small bug due to a typo that I corrected.
