### ISSUE TITLE
'Interval' call error

### ISSUE THREAD

**Issue by TomyYamy** [nickovic/rtamt#4]
I'm trying [f0c6720] at pyt23. 
I find a issue related to 'Interval'. I think some of wrapper setting has issue...
```
$ python3 monitor_stl_ct.py
Traceback (most recent call last):
  File "monitor_stl_ct.py", line 3, in <module>
    import rtamt
  File "/usr/local/lib/python3.6/dist-packages/rtamt/__init__.py", line 1, in <module>
    from rtamt.spec.stl.specification import STLSpecification
  File "/usr/local/lib/python3.6/dist-packages/rtamt/spec/stl/specification.py", line 17, in <module>
    from rtamt.parser.stl.StlLexer import StlLexer
  File "/usr/local/lib/python3.6/dist-packages/rtamt/parser/stl/StlLexer.py", line 316, in <module>
    class StlLexer(Lexer):
  File "/usr/local/lib/python3.6/dist-packages/rtamt/parser/stl/StlLexer.py", line 318, in StlLexer
    atn = ATNDeserializer().deserialize(serializedATN())
  File "/usr/local/lib/python3.6/dist-packages/antlr4/atn/ATNDeserializer.py", line 87, in deserialize
    sets = self.readSets(atn)
  File "/usr/local/lib/python3.6/dist-packages/antlr4/atn/ATNDeserializer.py", line 211, in readSets
    iset.addRange(Interval(i1, i2 + 1)) # range upper limit is exclusive
NameError: name 'Interval' is not defined
```

Temporally I'm using 18.04 on Windows 10 (windows power shell). Maybe it does not matter.

**Comment by TomyYamy** [comment]
Sorry, I find my fault.
Actually I have installed antlr4-ypthon3-runtime that time, but the version was old, ver 4.5.
I found we need ver 4.8.
