### ISSUE TITLE
Location of switching C++/Python.

### ISSUE THREAD

**Issue by TomyYamy** [nickovic/rtamt#96]
in commit: 1885a2b2e2a3e33964c309c6e82d5d4b9ba6c387 branch: ast-refactoring

It locates,
rtamt/rtamt/ast/parser/stl/specification_parser.py
class STLSpecificationParser(LTLSpecificationParser, StlParserVisitor):
    
    def __init__(self, spec):
        self.ops = set()
        self.spec = spec

        io_type_name = 'rtamt.lib.rtamt_stl_library_wrapper.stl_io_type'
        comp_op_name = 'rtamt.lib.rtamt_stl_library_wrapper.stl_comp_op'
        if self.spec.language == Language.PYTHON:
            io_type_name = 'rtamt.enumerations.io_type'
            comp_op_name = 'rtamt.enumerations.comp_op'

        self.io_type_mod = __import__(io_type_name, fromlist=[''])
        self.comp_op_mod = __import__(comp_op_name, fromlist=[''])

It difficult to library user specify it in ast layer.

**Comment by TomyYamy** [comment]
@nickovic 
My suggestion is move this to semantic layer.
Do you think it is possible that separate the switch from AST layer?

**Comment by TomyYamy** [comment]
It relates #120 
@nickovic 
Do you think we can implement StlAstVisitorCpp that has all C++ wrapper by inheriting StlAstVisitor?
I did not understand how to wrap and connect C++(semantics) and python (syntax) with boost.

**Comment by TomyYamy** [comment]
We find we can do it easy  in semantic layer.

**Comment by TomyYamy** [comment]
Now it is on going at cpp_refactoring branch.

**Comment by TomyYamy** [comment]
@nickovic I have isse to call cpp module. Please help me later.

**Comment by TomyYamy** [comment]
@nickovic Do we have only discrete time online in cpp?

**Comment by TomyYamy** [comment]
I understand it is only for discrete time online in cpp.

**Comment by TomyYamy** [comment]
@nickovic I'm reliving cpp in cpp_refactoring
The cpp build seems to work almost with Ubuntu18.04/Python2 but I have minor trouble.

        /rtamt/tests/python/api$ python2 test_stl_discrete_time_online_specification_cpp.py 
        Traceback (most recent call last):
          File "test_stl_discrete_time_online_specification_cpp.py", line 3, in <module>
            import rtamt
          File "/mnt/data/repos/rtamt/rtamt/__init__.py", line 17, in <module>
            from rtamt.spec.stl.discrete_time.specification import STLDiscreteTimeSpecification
          File "/mnt/data/repos/rtamt/rtamt/spec/stl/discrete_time/specification.py", line 7, in <module>
            from rtamt.operation.stl.discrete_time.online.cpp.evaluator import StlDiscreteTimeOnlineEvaluatorCpp
          File "/mnt/data/repos/rtamt/rtamt/operation/stl/discrete_time/online/cpp/evaluator.py", line 1, in <module>
            from rtamt.operation.stl.discrete_time.online.cpp.ast_visitor import StlDiscreteTimeOnlineAstVisitorCpp
          File "/mnt/data/repos/rtamt/rtamt/operation/stl/discrete_time/online/cpp/ast_visitor.py", line 11, in <module>
            from rtamt.lib.rtamt_stl_library_wrapper.stl_and_node import AndOperation
        RuntimeError: extension class wrapper for base class stl_library::StlCombinatorialBinaryNode has not been created yet

Could you please give me a hint to solve this?

**Comment by TomyYamy** [comment]
@nickovic OK, finally I fixed this call bug in cpp_refactoring.
However, still there are minor issue in test. Could you please check those?
/rtamt/tests/cpp/test_stl_evaluation_cpp.py
/rtamt/tests/python/api/test_stl_discrete_time_online_specification_cpp.py

**Comment by TomyYamy** [comment]
@nickovic 
I fixed issue of 
/rtamt/tests/cpp/test_stl_evaluation_cpp.py

We have issue on 
/rtamt/tests/cpp/test_stl_sampling_time_units_cpp.py
But it should be fixed when we merge set_sampling_period branch.

only problem is 
/rtamt/tests/python/api/test_stl_discrete_time_online_specification_cpp.py
but it should be just unsupported operator issue. I can fix it if I have time.

**Comment by TomyYamy** [comment]
We are done.
